[book]
authors = ["O2HCHO"]
language = "en"
src = "src"
title = "My Notes"

[output.html]
table-of-contents = true
git-repository-url = "https://github.com/O2HCHO/my-notes"

[preprocessor.katex]
macros = {}